/**
 * Report Webview - Full HTML report in webview panel
 * Reuses HtmlReporter output style from Python library.
 */

import * as vscode from 'vscode';
import { AnalysisResult, Issue, Severity, IssueSummary } from '../models/types';

let currentPanel: vscode.WebviewPanel | undefined;

/**
 * Show the analysis report in a webview panel.
 */
export function showReportWebview(
    context: vscode.ExtensionContext,
    results: AnalysisResult[],
): void {
    if (currentPanel) {
        currentPanel.reveal();
        currentPanel.webview.html = generateHtml(results);
        return;
    }

    currentPanel = vscode.window.createWebviewPanel(
        'catalystops.report',
        'CatalystOps Report',
        vscode.ViewColumn.Beside,
        { enableScripts: true },
    );

    currentPanel.webview.html = generateHtml(results);

    currentPanel.onDidDispose(() => {
        currentPanel = undefined;
    });
}

function generateHtml(results: AnalysisResult[]): string {
    // Aggregate all issues across results
    const allIssues = results.flatMap(r => r.issues);
    const summary = computeSummary(allIssues);
    const sortedIssues = [...allIssues].sort((a, b) => {
        const order: Record<string, number> = { critical: 1, warning: 2, info: 3, suggestion: 4 };
        return (order[a.severity] ?? 4) - (order[b.severity] ?? 4);
    });

    const issuesHtml = sortedIssues.length === 0
        ? '<div class="no-issues"><p>No optimization issues detected!</p><p>Your Spark job appears to be well optimized.</p></div>'
        : sortedIssues.map(issueCard).join('\n');

    const clusterHtml = results.length > 0 && results[0].cluster
        ? clusterSection(results[0].cluster)
        : '';

    const planHtml = results.length > 0 && results[0].executionPlan?.physicalPlan
        ? planSection(results[0].executionPlan)
        : '';

    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CatalystOps Report</title>
    <style>${cssStyles()}</style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>CatalystOps Report</h1>
            <div class="metadata">
                <span class="timestamp">Generated: ${new Date().toISOString().replace('T', ' ').substring(0, 19)}</span>
                ${results.map(r => r.dataframeName ? `<span class="dataframe">DataFrame: ${escapeHtml(r.dataframeName)}</span>` : '').join(' ')}
            </div>
        </div>
        <div class="summary">
            <h2>Summary</h2>
            <div class="summary-cards">
                <div class="summary-card critical"><div class="count">${summary.critical}</div><div class="label">Critical</div></div>
                <div class="summary-card warning"><div class="count">${summary.warnings}</div><div class="label">Warnings</div></div>
                <div class="summary-card info"><div class="count">${summary.info}</div><div class="label">Info</div></div>
                <div class="summary-card suggestion"><div class="count">${summary.suggestions}</div><div class="label">Suggestions</div></div>
            </div>
        </div>
        ${clusterHtml}
        ${planHtml}
        <div class="section">
            <h2>Issues & Recommendations</h2>
            <div class="issues-list">${issuesHtml}</div>
        </div>
        <div class="footer"><p>Generated by CatalystOps</p></div>
    </div>
    <script>${jsScript()}</script>
</body>
</html>`;
}

function issueCard(issue: Issue): string {
    const severityClass = issue.severity;
    const locationHtml = issue.location ? `<p class="location">Location: ${escapeHtml(issue.location)}</p>` : '';
    const impactHtml = issue.impact ? `<p class="impact">Impact: ${escapeHtml(issue.impact)}</p>` : '';

    let configHtml = '';
    if (issue.fix?.configChanges && Object.keys(issue.fix.configChanges).length > 0) {
        const items = Object.entries(issue.fix.configChanges)
            .map(([k, v]) => `<div class="config-change"><code>spark.conf.set("${escapeHtml(k)}", "${escapeHtml(v)}")</code></div>`)
            .join('');
        configHtml = `<div class="config-changes"><h5>Configuration Changes</h5>${items}</div>`;
    }

    let codeHtml = '';
    if (issue.fix?.code) {
        codeHtml = `<div class="code-block"><h5>Code Example</h5><pre>${escapeHtml(issue.fix.code)}</pre></div>`;
    }

    return `
    <div class="issue-card ${severityClass}">
        <div class="issue-header">
            <span class="severity-badge">${issue.severity.toUpperCase()}</span>
            <span class="category-badge">${issue.category}</span>
            <h3>${escapeHtml(issue.title)}</h3>
        </div>
        <div class="issue-body">
            ${locationHtml}
            <p class="description">${escapeHtml(issue.description)}</p>
            ${impactHtml}
            <div class="fix">
                <h4>Recommended Fix</h4>
                <p>${escapeHtml(issue.fix?.description || '')}</p>
                ${configHtml}
                ${codeHtml}
            </div>
        </div>
    </div>`;
}

function clusterSection(cluster: any): string {
    return `
    <div class="section">
        <h2>Cluster Configuration</h2>
        <div class="cluster-info">
            <table>
                <tr><td>Cluster Name</td><td>${escapeHtml(cluster.clusterName || 'Unknown')}</td></tr>
                <tr><td>Workers</td><td>${cluster.workers || 0}</td></tr>
                <tr><td>Total Cores</td><td>${cluster.totalCores || 0}</td></tr>
                <tr><td>Executor Memory</td><td>${escapeHtml(cluster.executorMemory || 'unknown')}</td></tr>
                <tr><td>Spark Version</td><td>${escapeHtml(cluster.sparkVersion || 'unknown')}</td></tr>
                <tr><td>AQE Enabled</td><td>${cluster.adaptiveQueryEnabled ? 'Yes' : 'No'}</td></tr>
            </table>
        </div>
    </div>`;
}

function planSection(plan: any): string {
    return `
    <div class="section collapsible">
        <h2 onclick="toggleSection(this)">Execution Plan &#x25BC;</h2>
        <div class="section-content">
            <div class="plan-stats">
                <div class="stat"><span>Stages:</span><span>${plan.totalStages || 0}</span></div>
                <div class="stat"><span>Shuffles:</span><span>${plan.totalShuffles || 0}</span></div>
                <div class="stat"><span>Joins:</span><span>${plan.joinCount || 0}</span></div>
            </div>
            <h3>Physical Plan</h3>
            <pre class="plan-text">${escapeHtml(plan.physicalPlan || '')}</pre>
        </div>
    </div>`;
}

function computeSummary(issues: Issue[]): IssueSummary {
    return {
        critical: issues.filter(i => i.severity === Severity.CRITICAL).length,
        warnings: issues.filter(i => i.severity === Severity.WARNING).length,
        info: issues.filter(i => i.severity === Severity.INFO).length,
        suggestions: issues.filter(i => i.severity === Severity.SUGGESTION).length,
    };
}

function escapeHtml(text: string): string {
    return text
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;');
}

function cssStyles(): string {
    return `
    :root { --critical-color: #dc3545; --warning-color: #ffc107; --info-color: #17a2b8; --suggestion-color: #6c757d; --bg-color: #f8f9fa; --card-bg: #ffffff; --text-color: #212529; --border-color: #dee2e6; }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: var(--bg-color); color: var(--text-color); line-height: 1.6; padding: 20px; }
    .container { max-width: 1200px; margin: 0 auto; }
    .header { text-align: center; padding: 30px 0; border-bottom: 2px solid var(--border-color); margin-bottom: 30px; }
    .header h1 { color: #2c3e50; margin-bottom: 10px; }
    .metadata { color: #666; font-size: 0.9em; }
    .metadata span { margin: 0 10px; }
    .summary { margin-bottom: 30px; }
    .summary h2 { margin-bottom: 15px; }
    .summary-cards { display: flex; gap: 20px; flex-wrap: wrap; }
    .summary-card { flex: 1; min-width: 150px; padding: 20px; border-radius: 8px; text-align: center; color: white; }
    .summary-card.critical { background: var(--critical-color); }
    .summary-card.warning { background: var(--warning-color); color: #212529; }
    .summary-card.info { background: var(--info-color); }
    .summary-card.suggestion { background: var(--suggestion-color); }
    .summary-card .count { font-size: 2.5em; font-weight: bold; }
    .summary-card .label { font-size: 0.9em; opacity: 0.9; }
    .section { background: var(--card-bg); border-radius: 8px; padding: 20px; margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
    .section h2 { margin-bottom: 15px; cursor: pointer; }
    .cluster-info table { width: 100%; border-collapse: collapse; }
    .cluster-info td { padding: 8px 12px; border-bottom: 1px solid var(--border-color); }
    .cluster-info td:first-child { font-weight: 600; width: 200px; color: #495057; }
    .plan-stats { display: flex; gap: 30px; margin-bottom: 20px; }
    .plan-stats .stat span:first-child { font-weight: 600; margin-right: 5px; }
    .plan-text { background: #272822; color: #f8f8f2; padding: 15px; border-radius: 4px; overflow-x: auto; font-size: 0.85em; max-height: 400px; overflow-y: auto; }
    .section-content { display: none; }
    .section.expanded .section-content { display: block; }
    .no-issues { text-align: center; padding: 40px; color: #28a745; }
    .issues-list { display: flex; flex-direction: column; gap: 15px; }
    .issue-card { border-radius: 8px; overflow: hidden; border-left: 4px solid; }
    .issue-card.critical { border-left-color: var(--critical-color); }
    .issue-card.warning { border-left-color: var(--warning-color); }
    .issue-card.info { border-left-color: var(--info-color); }
    .issue-card.suggestion { border-left-color: var(--suggestion-color); }
    .issue-header { background: #f1f3f4; padding: 15px; display: flex; align-items: center; gap: 10px; flex-wrap: wrap; }
    .issue-header h3 { flex: 1; margin: 0; font-size: 1.1em; }
    .severity-badge, .category-badge { padding: 3px 8px; border-radius: 4px; font-size: 0.75em; font-weight: 600; text-transform: uppercase; }
    .critical .severity-badge { background: var(--critical-color); color: white; }
    .warning .severity-badge { background: var(--warning-color); color: #212529; }
    .info .severity-badge { background: var(--info-color); color: white; }
    .suggestion .severity-badge { background: var(--suggestion-color); color: white; }
    .category-badge { background: #e9ecef; color: #495057; }
    .issue-body { padding: 15px; }
    .issue-body p { margin-bottom: 10px; }
    .location { color: #666; font-size: 0.9em; }
    .impact { color: #856404; background: #fff3cd; padding: 8px; border-radius: 4px; }
    .fix { margin-top: 15px; padding-top: 15px; border-top: 1px solid var(--border-color); }
    .fix h4 { color: #28a745; margin-bottom: 10px; }
    .fix h5 { margin: 10px 0 5px; color: #495057; font-size: 0.9em; }
    .code-block pre { background: #272822; color: #f8f8f2; padding: 15px; border-radius: 4px; overflow-x: auto; font-size: 0.85em; }
    .config-change code { background: #e9ecef; padding: 5px 10px; border-radius: 4px; display: inline-block; margin: 3px 0; }
    .footer { text-align: center; padding: 20px; color: #666; font-size: 0.9em; }
    `;
}

function jsScript(): string {
    return `
    function toggleSection(header) {
        const section = header.closest('.section');
        section.classList.toggle('expanded');
    }
    document.addEventListener('DOMContentLoaded', function() {
        const first = document.querySelector('.collapsible');
        if (first) first.classList.add('expanded');
    });
    `;
}
